version: 2
jobs:
  build:
    docker:
    working_directory: ~/myapp
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          command: python -m venv env
      - restore_cache:
          keys:
            - v1-myapp-{{ checksum "requirements.txt" }}
      - run:
          name: Test
          command: |
            . env/bin/activate
            pip install pytest
            pip install mock
            python ./...
      - save_cache:
          key: v1-myapp-{{ checksum "requirements.txt" }}
          paths:
            - ~/myapp/env
